# Generated by Django 5.1.4 on 2025-01-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivariety',
            name='image',
            field=models.ImageField(upload_to='chais/'),
        ),
    ]
