# Generated by Django 5.1.4 on 2025-01-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_chaivariety_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivariety',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
