# Generated by Django 5.1.4 on 2025-01-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0005_alter_chaivariety_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivariety',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
