# Generated by Django 5.1.4 on 2025-01-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0006_alter_chaivariety_price'),
    ]

    operations = [
    ]
