# Generated by Django 5.1.4 on 2025-01-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0007_auto_20250112_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='detail_chai/'),
        ),
    ]
